const meta = require("libphonenumber-js/metadata.full.json");
const examples = require("libphonenumber-js/examples.mobile.json");

const COUNTRY_CODES = [
  ["BW", "+267"],
  ["ZA", "+27"],
  ["NA", "+264"],
  ["ZM", "+260"],
  ["AF", "+93"],
  ["AL", "+355"],
  ["DZ", "+213"],
  ["AR", "+54"],
  ["AM", "+374"],
  ["AU", "+61"],
  ["AT", "+43"],
  ["AZ", "+994"],
  ["BH", "+973"],
  ["BD", "+880"],
  ["BE", "+32"],
  ["BJ", "+229"],
  ["BO", "+591"],
  ["BA", "+387"],
  ["BR", "+55"],
  ["BN", "+673"],
  ["BG", "+359"],
  ["BF", "+226"],
  ["BI", "+257"],
  ["KH", "+855"],
  ["CM", "+237"],
  ["CA", "+1"],
  ["TD", "+235"],
  ["CL", "+56"],
  ["CN", "+86"],
  ["CO", "+57"],
  ["CD", "+243"],
  ["CG", "+242"],
  ["CR", "+506"],
  ["HR", "+385"],
  ["CU", "+53"],
  ["CY", "+357"],
  ["CZ", "+420"],
  ["DK", "+45"],
  ["DJ", "+253"],
  ["EC", "+593"],
  ["EG", "+20"],
  ["SV", "+503"],
  ["ER", "+291"],
  ["EE", "+372"],
  ["SZ", "+268"],
  ["ET", "+251"],
  ["FJ", "+679"],
  ["FI", "+358"],
  ["FR", "+33"],
  ["GA", "+241"],
  ["GM", "+220"],
  ["GE", "+995"],
  ["DE", "+49"],
  ["GH", "+233"],
  ["GR", "+30"],
  ["GT", "+502"],
  ["GN", "+224"],
  ["GY", "+592"],
  ["HT", "+509"],
  ["HN", "+504"],
  ["HK", "+852"],
  ["HU", "+36"],
  ["IS", "+354"],
  ["IN", "+91"],
  ["ID", "+62"],
  ["IR", "+98"],
  ["IQ", "+964"],
  ["IE", "+353"],
  ["IL", "+972"],
  ["IT", "+39"],
  ["CI", "+225"],
  ["JM", "+1-876"],
  ["JP", "+81"],
  ["JO", "+962"],
  ["KZ", "+7"],
  ["KE", "+254"],
  ["KW", "+965"],
  ["KG", "+996"],
  ["LA", "+856"],
  ["LV", "+371"],
  ["LB", "+961"],
  ["LR", "+231"],
  ["LY", "+218"],
  ["LT", "+370"],
  ["LU", "+352"],
  ["MG", "+261"],
  ["MW", "+265"],
  ["MY", "+60"],
  ["ML", "+223"],
  ["MT", "+356"],
  ["MR", "+222"],
  ["MU", "+230"],
  ["MX", "+52"],
  ["MD", "+373"],
  ["MC", "+377"],
  ["MN", "+976"],
  ["ME", "+382"],
  ["MA", "+212"],
  ["MZ", "+258"],
  ["MM", "+95"],
  ["NP", "+977"],
  ["NL", "+31"],
  ["NZ", "+64"],
  ["NE", "+227"],
  ["NG", "+234"],
  ["KP", "+850"],
  ["MK", "+389"],
  ["NO", "+47"],
  ["OM", "+968"],
  ["PK", "+92"],
  ["PS", "+970"],
  ["PA", "+507"],
  ["PY", "+595"],
  ["PE", "+51"],
  ["PH", "+63"],
  ["PL", "+48"],
  ["PT", "+351"],
  ["QA", "+974"],
  ["RO", "+40"],
  ["RU", "+7"],
  ["RW", "+250"],
  ["SA", "+966"],
  ["SN", "+221"],
  ["RS", "+381"],
  ["SL", "+232"],
  ["SG", "+65"],
  ["SK", "+421"],
  ["SI", "+386"],
  ["SO", "+252"],
  ["KR", "+82"],
  ["SS", "+211"],
  ["ES", "+34"],
  ["LK", "+94"],
  ["SD", "+249"],
  ["SR", "+597"],
  ["SE", "+46"],
  ["CH", "+41"],
  ["SY", "+963"],
  ["TW", "+886"],
  ["TJ", "+992"],
  ["TZ", "+255"],
  ["TH", "+66"],
  ["TG", "+228"],
  ["TN", "+216"],
  ["TR", "+90"],
  ["TM", "+993"],
  ["UG", "+256"],
  ["UA", "+380"],
  ["AE", "+971"],
  ["GB", "+44"],
  ["US", "+1"],
  ["UY", "+598"],
  ["UZ", "+998"],
  ["VE", "+58"],
  ["VN", "+84"],
  ["YE", "+967"],
  ["ZW", "+263"],
];

const MIN_LENGTH = 6;

const OVERRIDES = {
  BW: [8],
};

const result = {};
let missing = [];
for (const [code, dial] of COUNTRY_CODES) {
  const entry = meta.countries[code];
  let lens = [];
  const exLen = examples[code] ? String(examples[code]).length : null;
  if (exLen) lens.push(exLen);
  if (entry) {
    const types = entry[11] || [];
    const fixedType = types[0];
    if (fixedType) {
      const fl = fixedType[1] || entry[3] || [];
      lens = lens.concat(fl);
    }
  }
  lens = [...new Set(lens)].filter((l) => l >= MIN_LENGTH).sort((a, b) => a - b);
  if (OVERRIDES[code]) lens = OVERRIDES[code];
  if (lens.length) {
    result[code] = lens;
  } else {
    missing.push(code + " (" + dial + ")");
  }
}

console.log("=== Generated ===");
console.log(JSON.stringify(result, null, 1));
console.log("=== Countries with no lengths ===");
console.log(missing.join(", ") || "none");

const fs = require("fs");
const path = require("path");

const lines = Object.keys(result)
  .sort()
  .map((c) => '"' + c + '":[' + result[c].join(",") + "]");
const compact = "{\n  " + lines.join(",\n  ") + "\n}";

const dialLines = COUNTRY_CODES.map(
  ([code, dial]) => '"' + dial + '":"' + code + '"',
);
const dialMap =
  "{\n  " + dialLines.join(",\n  ") + "\n}";

const frontend = path.resolve(__dirname, "../../public/phone-lengths.js");
const backend = path.resolve(__dirname, "../../backend/phone-rules.js");

fs.writeFileSync(
  frontend,
  "/* Generated by tools/phone-rules/generate.js — do not edit manually. */\n" +
    "var PHONE_LENGTHS = " +
    compact +
    ";\n",
);

fs.writeFileSync(
  backend,
  "// Generated by tools/phone-rules/generate.js — do not edit manually.\n" +
    "const PHONE_LENGTHS = " +
    compact +
    ";\n" +
    "\n" +
    "// Dial code -> country code lookup (must stay in sync with public/script.js COUNTRY_CODES)\n" +
    "const DIAL_TO_CODE = " +
    dialMap +
    ";\n" +
    "\n" +
    "module.exports = { PHONE_LENGTHS, DIAL_TO_CODE };\n",
);

console.log("\nWrote " + frontend);
console.log("Wrote " + backend);
