services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    environment:
      - PORT=3000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CONTACT_EMAIL=${CONTACT_EMAIL}

    expose:
      - "3000"
    restart: unless-stopped
